#!/usr/bin/env bash
# =============================================================================
#  DeepSeek Harness relaunch helper (GENERATED by @local/dsh-ian-daemon)
#
#  Used by the plugin's "重启" action when the running Harness was NOT started
#  by systemd (for example `dsh web` typed in a terminal). The action has to
#  hand the port over before it can be reclaimed, so this helper is spawned
#  detached, waits for the old process to disappear, and then either restarts
#  the systemd unit (when autostart is enabled) or re-executes the exact
#  command line the old process was started with.
#
#  usage: relaunch.sh <pid> <systemd|exec> <unit> <cwd> [command...]
# =============================================================================
set -uo pipefail

OLD_PID="${1:-0}"
MODE="${2:-exec}"
UNIT="${3:-}"
CWD="${4:-}"
shift 4 2>/dev/null || true

# Wait up to 30s for the old Harness process to release the port.
for _ in $(seq 1 300); do
  [ "$OLD_PID" -gt 1 ] || break
  kill -0 "$OLD_PID" 2>/dev/null || break
  sleep 0.1
done
sleep 0.6

if [ "$MODE" = "systemd" ] && [ -n "$UNIT" ]; then
  if systemctl --user restart "$UNIT" >/dev/null 2>&1; then
    exit 0
  fi
  # `systemctl --user` can be unavailable in restricted/namespaced sessions;
  # fall back to the same D-Bus call systemd exposes.
  if busctl --user call org.freedesktop.systemd1 /org/freedesktop/systemd1 \
    org.freedesktop.systemd1.Manager RestartUnit ss "$UNIT" replace >/dev/null 2>&1; then
    exit 0
  fi
  exit 1
fi

[ -n "$CWD" ] && cd "$CWD" 2>/dev/null
if [ "$#" -eq 0 ]; then
  exit 1
fi
exec "$@"
