#!/usr/bin/env bash
# =============================================================================
#  DeepSeek Harness supervisor
#
#  GENERATED by the @local/dsh-ian-daemon plugin — do not edit by hand; the
#  plugin rewrites this file whenever its configuration changes.
#
#  systemd starts this script (see ~/.config/systemd/user/dsh-ian-daemon.service).
#  The script owns the crash / corruption recovery ladder:
#
#    1. preflight  validate the composed profile config before every start and
#                  restore the last known-good copy when it is corrupt
#    2. supervise  run `dsh`, measure how long it stayed up, and count rapid
#                  failures inside a rolling window
#    3. escalate   after FAIL_THRESHOLD rapid failures, boot the pristine safe
#                  profile instead, write an incident report to
#                  <autostart-home>/reports, and notify the desktop
#
#  Safe mode is sticky: it stays until it is explicitly reset (the plugin's
#  "复位并重启" action, or by deleting <state>/mode and restarting the unit).
#
#  Every DSH_IAN_DAEMON_* value below can be overridden from the environment, so
#  the whole ladder can be exercised without touching the real profile.
# =============================================================================
set -uo pipefail

# --- baked configuration -----------------------------------------------------
AUTOSTART_HOME="${DSH_IAN_DAEMON_HOME:-@@HOME_DIR@@}"
NODE_BIN="${DSH_IAN_DAEMON_NODE:-@@NODE_BIN@@}"
DSH_CLI="${DSH_IAN_DAEMON_CLI:-@@DSH_CLI@@}"
DSH_HOME_DIR="${DSH_IAN_DAEMON_DSH_HOME:-@@DSH_HOME@@}"
PROFILE="${DSH_IAN_DAEMON_PROFILE:-@@PROFILE@@}"
SAFE_PROFILE="${DSH_IAN_DAEMON_SAFE_PROFILE:-@@SAFE_PROFILE@@}"
SAFE_TEMPLATE="${DSH_IAN_DAEMON_SAFE_TEMPLATE:-@@SAFE_TEMPLATE@@}"
APP_ARGS="${DSH_IAN_DAEMON_APP_ARGS:-@@APP_ARGS@@}"
UNIT_NAME="${DSH_IAN_DAEMON_UNIT:-@@UNIT_NAME@@}"
FAIL_WINDOW="${DSH_IAN_DAEMON_FAIL_WINDOW:-@@FAIL_WINDOW@@}"
FAIL_THRESHOLD="${DSH_IAN_DAEMON_FAIL_THRESHOLD:-@@FAIL_THRESHOLD@@}"
HEALTHY_SECONDS="${DSH_IAN_DAEMON_HEALTHY_SECONDS:-@@HEALTHY_SECONDS@@}"
MAX_BACKOFF="${DSH_IAN_DAEMON_MAX_BACKOFF:-@@MAX_BACKOFF@@}"
NOTIFY="${DSH_IAN_DAEMON_NOTIFY:-@@NOTIFY@@}"

# --- test hooks (never set by the unit) --------------------------------------
EXEC_OVERRIDE="${DSH_IAN_DAEMON_EXEC:-}"
SKIP_PREFLIGHT="${DSH_IAN_DAEMON_SKIP_PREFLIGHT:-0}"
SKIP_SAFE_PROFILE="${DSH_IAN_DAEMON_SKIP_SAFE_PROFILE:-0}"

STATE_DIR="$AUTOSTART_HOME/state"
REPORT_DIR="$AUTOSTART_HOME/reports"
LOG_DIR="$AUTOSTART_HOME/logs"
BACKUP_DIR="$AUTOSTART_HOME/backup"
PROFILE_DIR="$DSH_HOME_DIR/profiles/$PROFILE"
LOG="$LOG_DIR/supervisor.log"
OUT_LOG="$LOG_DIR/dsh.out.log"
CONFIG_FILES=(cordis.yml cordis.patch.yml package.json pnpm-workspace.yaml)

mkdir -p "$STATE_DIR" "$REPORT_DIR" "$LOG_DIR" "$BACKUP_DIR" 2>/dev/null || true

# --- small helpers -----------------------------------------------------------
now() { date +%s; }
stamp() { date -Is; }

log() {
  printf '%s [supervisor] %s\n' "$(stamp)" "$*" >>"$LOG" 2>/dev/null || true
}

read_state() { # file default
  local value=""
  [ -f "$1" ] && value="$(cat "$1" 2>/dev/null)"
  case "$value" in ''|*[!0-9]*) printf '%s' "$2" ;; *) printf '%s' "$value" ;; esac
}

write_state() { printf '%s' "$2" >"$1" 2>/dev/null || true; }

notify() { # urgency message
  [ "$NOTIFY" = "1" ] || return 0
  command -v notify-send >/dev/null 2>&1 || return 0
  notify-send -a "DeepSeek Harness" -u "${1:-normal}" "DeepSeek Harness" "$2" >/dev/null 2>&1 || true
}

# A sleep that still reacts to `systemctl stop` instead of holding shutdown for
# up to MAX_BACKOFF seconds.
interruptible_sleep() {
  sleep "$1" &
  local sleeper=$!
  wait "$sleeper" 2>/dev/null
  kill "$sleeper" 2>/dev/null || true
}

# Report an unusable generated command line at most once per failure window.
report_missing_runtime() {
  local marker="$STATE_DIR/runtime-missing.reported" age=999999
  [ -f "$marker" ] && age=$(( $(now) - $(read_state "$marker" 0) ))
  if [ "$age" -gt "$FAIL_WINDOW" ]; then
    write_state "$marker" "$(now)"
    write_incident "runtime-missing" "The generated command line cannot be used: node='$NODE_BIN' cli='$DSH_CLI'. Nothing was started, so this is NOT a clean shutdown. Regenerate the autostart files (POST /dsh-ian-daemon/install, or reinstall the plugin) and restart $UNIT_NAME."
    notify critical "DeepSeek Harness 无法启动：node/dsh 路径失效，已写入报告，不会静默退出。"
  fi
  log "runtime unresolved: node='$NODE_BIN' cli='$DSH_CLI'; nothing started"
}

rotate_logs() {  if [ -f "$LOG" ] && [ "$(wc -l <"$LOG" 2>/dev/null || echo 0)" -gt 4000 ]; then
    tail -n 800 "$LOG" >"$LOG.rot" 2>/dev/null && mv -f "$LOG.rot" "$LOG"
  fi
  if [ -f "$OUT_LOG" ] && [ "$(wc -l <"$OUT_LOG" 2>/dev/null || echo 0)" -gt 8000 ]; then
    tail -n 2000 "$OUT_LOG" >"$OUT_LOG.rot" 2>/dev/null && mv -f "$OUT_LOG.rot" "$OUT_LOG"
  fi
  # keep the 20 newest incident reports
  ls -1t "$REPORT_DIR"/incident-*.md 2>/dev/null | tail -n +21 | while read -r old; do
    rm -f "$old"
  done
}

# --- state snapshot / restore ------------------------------------------------
snapshot_config() {
  [ -d "$PROFILE_DIR" ] || return 0
  local copied=0 file
  for file in "${CONFIG_FILES[@]}"; do
    if [ -f "$PROFILE_DIR/$file" ]; then
      cp -f "$PROFILE_DIR/$file" "$BACKUP_DIR/$file" 2>/dev/null && copied=$((copied + 1))
    fi
  done
  if [ "$copied" -gt 0 ]; then
    stamp >"$BACKUP_DIR/.snapshot-at"
    log "preflight: snapshot of $copied config file(s) refreshed"
  fi
}

restore_config() {
  local file
  for file in "${CONFIG_FILES[@]}"; do
    [ -f "$BACKUP_DIR/$file" ] || continue
    cp -f "$BACKUP_DIR/$file" "$PROFILE_DIR/$file" 2>/dev/null || true
  done
}

quarantine_config() {
  local dir="$REPORT_DIR/broken-$(date +%Y%m%d-%H%M%S)" file
  mkdir -p "$dir" 2>/dev/null || return 0
  for file in "${CONFIG_FILES[@]}"; do
    [ -f "$PROFILE_DIR/$file" ] && cp -f "$PROFILE_DIR/$file" "$dir/$file" 2>/dev/null
  done
  printf '%s' "$dir"
}

# --- reporting ---------------------------------------------------------------
write_incident() { # kind message
  local kind="$1" message="$2" ts
  ts="$(stamp)"
  cat >"$STATE_DIR/incident.json" <<JSON
{"at":"$ts","kind":"$kind","mode":"$mode","failures":$failures,"failureThreshold":$FAIL_THRESHOLD,"windowSeconds":$FAIL_WINDOW,"lastExit":$last_exit,"uptimeSeconds":$uptime,"profile":"$PROFILE","safeProfile":"$SAFE_PROFILE","message":"$message"}
JSON
  {
    printf '# DeepSeek Harness incident — %s\n\n' "$ts"
    printf -- '- kind: `%s`\n' "$kind"
    printf -- '- mode: `%s`\n' "$mode"
    printf -- '- rapid failures: %s (threshold %s inside %ss)\n' "$failures" "$FAIL_THRESHOLD" "$FAIL_WINDOW"
    printf -- '- last child exit code: %s\n' "$last_exit"
    printf -- '- last run uptime: %ss (healthy means >= %ss)\n' "$uptime" "$HEALTHY_SECONDS"
    printf -- '- profile: `%s`   safe profile: `%s`\n' "$PROFILE" "$SAFE_PROFILE"
    printf -- '- report dir: `%s`\n\n' "$REPORT_DIR"
    printf '## What happened\n\n%s\n\n' "$message"
    printf '## Leaving safe mode\n\n```\n'
    printf 'rm -f %s/mode %s/failures\n' "$STATE_DIR" "$STATE_DIR"
    printf 'systemctl --user restart %s\n' "$UNIT_NAME"
    printf '```\n\n'
    printf '## Supervisor log (tail)\n\n```\n'
    tail -n 40 "$LOG" 2>/dev/null
    printf '```\n\n## dsh output (tail)\n\n```\n'
    tail -n 30 "$OUT_LOG" 2>/dev/null
    printf '```\n'
  } >"$REPORT_DIR/incident-$ts.md" 2>/dev/null || true
  cp -f "$REPORT_DIR/incident-$ts.md" "$REPORT_DIR/latest.md" 2>/dev/null || true
  log "incident written: $REPORT_DIR/incident-$ts.md ($kind)"
  rotate_logs
}

# --- runtime resolution ------------------------------------------------------
# A generated unit goes stale: fnm removes versioned node directories, the dsh
# install moves, or a bad generation bakes empty paths. Launching a broken
# command line is worse than not launching at all — `node ""` finds no script,
# reads EOF on stdin and exits 0, which looks exactly like a clean shutdown.
# Repair what can be repaired; treat the rest as a failure, never as a clean stop.
resolve_runtime() {
  local repaired=0 candidate
  if [ ! -x "$NODE_BIN" ]; then
    for candidate in "$(command -v node 2>/dev/null || true)" \
      "$HOME"/.local/share/fnm/node-versions/*/installation/bin/node \
      /usr/local/bin/node /usr/bin/node; do
      if [ -n "$candidate" ] && [ -x "$candidate" ]; then
        NODE_BIN="$candidate"
        repaired=1
        break
      fi
    done
  fi
  if [ ! -f "$DSH_CLI" ]; then
    for candidate in "$(dirname "${NODE_BIN:-/nonexistent}" 2>/dev/null)/../lib/node_modules/@deepseek-ai/dsh/lib/bin.js" \
      "$HOME"/.local/share/fnm/node-versions/*/lib/node_modules/@deepseek-ai/dsh/lib/bin.js \
      "$HOME"/.local/share/fnm/node-versions/*/installation/lib/node_modules/@deepseek-ai/dsh/lib/bin.js \
      /usr/local/lib/node_modules/@deepseek-ai/dsh/lib/bin.js \
      /usr/lib/node_modules/@deepseek-ai/dsh/lib/bin.js; do
      if [ -n "$candidate" ] && [ -f "$candidate" ]; then
        DSH_CLI="$candidate"
        repaired=1
        break
      fi
    done
  fi
  [ "$repaired" = "1" ] && log "runtime repaired: node=$NODE_BIN cli=$DSH_CLI"
  [ -x "$NODE_BIN" ] && [ -f "$DSH_CLI" ]
}

# --- preflight ---------------------------------------------------------------
preflight() {
  local err="$STATE_DIR/preflight.err" started elapsed
  started="$(date +%s%3N)"
  if "$NODE_BIN" "$DSH_CLI" --profile "$PROFILE" --dump-config >/dev/null 2>"$err"; then
    elapsed=$(( $(date +%s%3N) - started ))
    log "preflight ok in ${elapsed}ms"
    [ -f "$BACKUP_DIR/cordis.patch.yml" ] || snapshot_config
    return 0
  fi

  local detail
  detail="$(tail -c 600 "$err" 2>/dev/null | tr '\n' ' ')"
  log "preflight: composed config for '$PROFILE' is invalid: $detail"

  if [ -f "$BACKUP_DIR/cordis.patch.yml" ]; then
    local quarantine
    quarantine="$(quarantine_config)"
    restore_config
    if "$NODE_BIN" "$DSH_CLI" --profile "$PROFILE" --dump-config >/dev/null 2>"$err"; then
      mode=normal
      write_incident "config-restored" "The composed profile config was invalid ('$detail'); it was restored from the last known-good snapshot. The broken copies are kept in $quarantine. Booting '$PROFILE' normally."
      notify normal "配置损坏，已从上次正常快照自动恢复并继续启动。"
      log "preflight: config restored from snapshot; continuing"
      return 0
    fi
    detail="$detail | after restore: $(tail -c 400 "$err" 2>/dev/null | tr '\n' ' ')"
  fi

  mode=safe
  write_state "$STATE_DIR/mode" safe
  write_incident "config-unrecoverable" "The composed profile config for '$PROFILE' cannot be composed and the last known-good snapshot did not fix it ('$detail'). Switching to safe mode."
  notify critical "配置无法恢复，已进入安全模式启动。"
  log "preflight: unrecoverable, entering safe mode"
  return 1
}

ensure_safe_profile() {
  [ "$SKIP_SAFE_PROFILE" = "1" ] && return 0
  local manifest="$DSH_HOME_DIR/profiles/$SAFE_PROFILE/package.json"
  [ -f "$manifest" ] && return 0
  log "safe mode: creating profile '$SAFE_PROFILE' from shipped template '$SAFE_TEMPLATE'"
  "$NODE_BIN" "$DSH_CLI" --profile "$SAFE_PROFILE" --from-default-profile "$SAFE_TEMPLATE" \
    --dump-config >/dev/null 2>"$STATE_DIR/safe-init.err" || true
  if [ -f "$manifest" ]; then
    log "safe mode: profile '$SAFE_PROFILE' ready"
    return 0
  fi
  log "safe mode: could not create '$SAFE_PROFILE': $(tail -c 300 "$STATE_DIR/safe-init.err" 2>/dev/null | tr '\n' ' ')"
  return 1
}

# --- main loop ---------------------------------------------------------------
failures="$(read_state "$STATE_DIR/failures" 0)"
window_start="$(read_state "$STATE_DIR/window_start" 0)"
last_exit="$(read_state "$STATE_DIR/last_exit" 0)"
uptime=0
stop=0
mode=normal
[ "$(cat "$STATE_DIR/mode" 2>/dev/null)" = "safe" ] && mode=safe
if [ "${1:-}" = "--force-safe" ]; then
  mode=safe
  log "started with --force-safe"
fi

read -r -a APP_ARGV <<<"$APP_ARGS"

log "supervisor started (pid $$, profile=$PROFILE, mode=$mode, failures=$failures, threshold=$FAIL_THRESHOLD, window=${FAIL_WINDOW}s, healthy=${HEALTHY_SECONDS}s)"
trap 'stop=1' TERM INT

while :; do
  if [ "$stop" = "1" ]; then
    log "stop requested before start; exiting"
    exit 0
  fi

  if [ -z "$EXEC_OVERRIDE" ] && ! resolve_runtime; then
    report_missing_runtime
    interruptible_sleep "$MAX_BACKOFF"
    continue
  fi

  if [ "$mode" = "normal" ] && [ "$SKIP_PREFLIGHT" != "1" ]; then
    preflight || true
  fi

  start_cmd=()
  use_safe="$mode"
  if [ "$mode" = "safe" ]; then
    if ensure_safe_profile; then
      start_cmd=("$NODE_BIN" "$DSH_CLI" "$SAFE_PROFILE" "${APP_ARGV[@]}")
      log "safe mode: booting profile '$SAFE_PROFILE'"
    else
      start_cmd=("$NODE_BIN" "$DSH_CLI" "$PROFILE" "${APP_ARGV[@]}")
      use_safe="safe-fallback"
      log "safe mode unavailable: falling back to '$PROFILE'"
      notify critical "安全模式不可用（无法创建 $SAFE_PROFILE），已回退到常规配置启动。"
    fi
  else
    start_cmd=("$NODE_BIN" "$DSH_CLI" "$PROFILE" "${APP_ARGV[@]}")
  fi

  start_ts="$(now)"
  write_state "$STATE_DIR/last_start" "$start_ts"
  printf '%s [supervisor] start mode=%s attempt_failures=%s cmd=%s\n' "$(stamp)" "$use_safe" "$failures" "${start_cmd[*]}" >>"$OUT_LOG" 2>/dev/null || true

  child=0
  if [ -n "$EXEC_OVERRIDE" ]; then
    log "start(test hook): $EXEC_OVERRIDE"
    # shellcheck disable=SC2086
    $EXEC_OVERRIDE >>"$OUT_LOG" 2>&1 &
    child=$!
  else
    "${start_cmd[@]}" >>"$OUT_LOG" 2>&1 &
    child=$!
  fi

  wait "$child"
  code=$?
  while [ "$stop" = "0" ] && kill -0 "$child" 2>/dev/null; do
    wait "$child"
    code=$?
  done

  if [ "$stop" = "1" ]; then
    kill -TERM "$child" 2>/dev/null || true
    wait "$child" 2>/dev/null || true
    log "supervisor stopped by signal; dsh terminated"
    exit 0
  fi

  uptime=$(( $(now) - start_ts ))
  last_exit="$code"
  write_state "$STATE_DIR/last_exit" "$last_exit"
  log "dsh exited code=$last_exit after ${uptime}s (mode=$use_safe)"

  if [ "$uptime" -ge "$HEALTHY_SECONDS" ]; then
    # One healthy run clears the ladder.
    if [ "$failures" != "0" ]; then
      log "healthy run: failure counter reset (was $failures)"
    fi
    failures=0
    window_start="$(now)"
    write_state "$STATE_DIR/failures" "$failures"
    write_state "$STATE_DIR/window_start" "$window_start"
    if [ "$use_safe" = "normal" ]; then
      snapshot_config
      rm -f "$STATE_DIR/incident.json" 2>/dev/null || true
    fi
    if [ "$code" = "0" ]; then
      # A clean exit still means the service should be up: this is an autostart
      # daemon, so restart it. Only a stop signal (systemctl stop) ends the
      # supervisor — that path is handled by the trap above.
      log "dsh exited cleanly after ${uptime}s; restarting anyway (only systemctl stop ends the service)"
      interruptible_sleep 5
      continue
    fi
  else
    if [ "$code" = "0" ]; then
      # An instant exit 0 is a broken start (for example `node ""` reading EOF),
      # never a clean shutdown: keep retrying and escalate like any other failure.
      log "dsh exited 0 after only ${uptime}s: treated as a failed start, not a clean stop"
    fi

    local_now="$(now)"
    if [ "$window_start" -eq 0 ] || [ $((local_now - window_start)) -gt "$FAIL_WINDOW" ]; then
      failures=1
      window_start="$local_now"
    else
      failures=$((failures + 1))
    fi
    write_state "$STATE_DIR/failures" "$failures"
    write_state "$STATE_DIR/window_start" "$window_start"

    if [ "$mode" = "normal" ] && [ "$failures" -ge "$FAIL_THRESHOLD" ]; then
      mode=safe
      write_state "$STATE_DIR/mode" safe
      write_incident "safe-mode" "dsh failed $failures times within $((local_now - window_start))s (last exit code $last_exit after ${uptime}s). The profile '$PROFILE' cannot boot reliably, so the supervisor switched to the safe profile '$SAFE_PROFILE'."
      notify critical "连续 $failures 次启动失败，已进入安全模式。详见 $REPORT_DIR/latest.md"
      log "escalation: $failures rapid failures -> safe mode"
    fi
  fi

  if [ "$mode" = "safe" ]; then
    backoff="$MAX_BACKOFF"
  else
    backoff=$((2 ** failures))
    [ "$backoff" -gt "$MAX_BACKOFF" ] && backoff="$MAX_BACKOFF"
  fi
  [ "$backoff" -lt 2 ] && backoff=2
  log "restarting in ${backoff}s"
  interruptible_sleep "$backoff"
done
