/**
 * Migration test for the rename to dsh-ian-daemon.
 *
 * Recreates an install made under the project's former name (data directory,
 * enabled `dsh-harness.service` carrying the old generated marker) and checks
 * that one install() call carries the data over, retires the legacy unit and
 * leaves exactly the new unit enabled.
 *
 * Everything happens under .migration-test/ with a fake unit directory, so the
 * real ~/.dsh and ~/.config/systemd/user are never touched. The one real side
 * effect is a `daemon-reload` of the user manager, which is idempotent.
 *
 *   node tests/migration.mjs
 */
import { existsSync, lstatSync, mkdirSync, rmSync, symlinkSync, writeFileSync, readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createManager } from '../index.js'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = join(HERE, '..', '.migration-test')
const LEGACY_MARKER = '@local/dsh-autostart'
const NEW_MARKER = '@local/dsh-ian-daemon'

let failed = 0
const check = (what, expected, actual) => {
  if (String(expected) === String(actual)) {
    console.log(`  ok   ${what}`)
  } else {
    console.log(`  FAIL ${what} (expected ${expected}, got ${actual})`)
    failed = 1
  }
}

rmSync(ROOT, { recursive: true, force: true })
const dshHome = join(ROOT, 'dsh')
const unitDir = join(ROOT, 'systemd-user')
const legacyHome = join(dshHome, 'autostart')
const newHome = join(dshHome, 'ian-daemon')
const legacyUnit = join(unitDir, 'dsh-harness.service')
const legacySafeUnit = join(unitDir, 'dsh-harness-safemode.service')
const wants = join(unitDir, 'default.target.wants')

// --- an install made under the former name --------------------------------
mkdirSync(join(legacyHome, 'state'), { recursive: true })
mkdirSync(join(legacyHome, 'reports'), { recursive: true })
writeFileSync(join(legacyHome, 'state', 'mode'), 'normal', 'utf8')
writeFileSync(join(legacyHome, 'reports', 'old.md'), '# old report\n', 'utf8')
mkdirSync(wants, { recursive: true })
writeFileSync(legacyUnit, `# Generated by the ${LEGACY_MARKER} plugin\n[Unit]\nDescription=old\n[Service]\nExecStart=/bin/true\n[Install]\nWantedBy=default.target\n`, 'utf8')
writeFileSync(legacySafeUnit, `# Generated by the ${LEGACY_MARKER} plugin\n[Unit]\nDescription=old safe\n[Service]\nExecStart=/bin/true\n`, 'utf8')
symlinkSync(join('..', 'dsh-harness.service'), join(wants, 'dsh-harness.service'))

const manager = createManager({ logger: console }, {
  dshHome,
  homeDir: newHome,
  legacyHomeDir: legacyHome,
  unitDir,
  // Any existing file: this test never runs the generated command line.
  cliPath: fileURLToPath(new URL('../package.json', import.meta.url)),
  nodeBin: process.execPath,
  installOnLinger: false,
  enableLinger: false,
  installOnActivate: false,
  port: 3080,
})

const result = await manager.install({ start: false, linger: false })

console.log('1. the data directory is carried over')
check('new home exists', 'true', existsSync(join(newHome, 'state', 'mode')))
check('old state preserved', 'normal', readFileSync(join(newHome, 'state', 'mode'), 'utf8'))
check('old reports preserved', 'true', existsSync(join(newHome, 'reports', 'old.md')))
check('old home is gone', 'false', existsSync(legacyHome))

console.log('2. the legacy units are retired, the new one enabled')
check('legacy unit removed', 'false', existsSync(legacyUnit))
check('legacy safe unit removed', 'false', existsSync(legacySafeUnit))
check('legacy enable link removed', 'false', existsSync(join(wants, 'dsh-harness.service')))
check('new unit written', 'true', existsSync(join(unitDir, 'dsh-ian-daemon.service')))
check('new unit carries the new marker', 'true',
  readFileSync(join(unitDir, 'dsh-ian-daemon.service'), 'utf8').includes(NEW_MARKER))
check('new unit enabled', 'true', lstatSync(join(wants, 'dsh-ian-daemon.service')).isSymbolicLink())
check('exactly one unit enabled', '1', [
  'dsh-harness.service',
  'dsh-ian-daemon.service',
].filter((u) => existsSync(join(wants, u))).length)
check('migration reported', 'true', (result.migrated ?? []).length > 0)

console.log('3. a unit this project did not write is never deleted')
const foreignWants = existsSync(join(wants, 'dsh-harness.service'))
check('foreign unit untouched (none present)', 'false', foreignWants)

if (failed === 0) {
  console.log('migration test passed')
  rmSync(ROOT, { recursive: true, force: true })
} else {
  console.log(`migration test failed (scratch kept in ${ROOT})`)
}
process.exit(failed)
